//
// Generated file, do not edit! Created by opp_msgc 4.0 from packet/QPacket.msg.
//

#ifndef _QPACKET_M_H_
#define _QPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0400
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>packet/QPacket.msg</tt> by opp_msgc.
 * <pre>
 * message qPacket extends cPacket
 * {
 *     int Id = 0;
 *     int app = -1;
 *     int dsNum = 0;
 *     int dsList[1024];
 *     long dsShares[1024];
 * }
 * </pre>
 */
class qPacket : public cPacket
{
  protected:
    int Id_var;
    int app_var;
    int dsNum_var;
    int dsList_var[1024];
    long dsShares_var[1024];

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const qPacket&);

  public:
    qPacket(const char *name=NULL, int kind=0);
    qPacket(const qPacket& other);
    virtual ~qPacket();
    qPacket& operator=(const qPacket& other);
    virtual qPacket *dup() const {return new qPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int Id_var);
    virtual int getApp() const;
    virtual void setApp(int app_var);
    virtual int getDsNum() const;
    virtual void setDsNum(int dsNum_var);
    virtual unsigned int getDsListArraySize() const;
    virtual int getDsList(unsigned int k) const;
    virtual void setDsList(unsigned int k, int dsList_var);
    virtual unsigned int getDsSharesArraySize() const;
    virtual long getDsShares(unsigned int k) const;
    virtual void setDsShares(unsigned int k, long dsShares_var);
};

inline void doPacking(cCommBuffer *b, qPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, qPacket& obj) {obj.parsimUnpack(b);}


#endif // _QPACKET_M_H_
